default:
	g++ SURF.cpp -o SURF `pkg-config opencv --cflags --libs` -lphidget21
blink:
	g++ blinky.cpp -o blinky `pkg-config opencv --cflags --libs` -lphidget21
hlo:
	g++ hello.cpp -o hello `pkg-config opencv --cflags --libs` -lphidget21
